# Generated by Django 2.1.1 on 2018-10-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Cadastrado'), ('AVAILABLE', 'Disponível'), ('RESERVED', 'Reservado'), ('DONATED', 'Doado')], default='REGISTERED', max_length=11),
        ),
    ]
