# Generated by Django 2.1.1 on 2018-10-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Alimentos'), ('ELETRO', 'Eletrônicos/Eletrodomésticos'), ('BOOK_OFFICE', 'Livraria/Papelaria'), ('FURNITURE', 'Móveis'), ('VOLUNTEER_WORK', 'Trabalho Voluntário'), ('HOUSEHOLD', 'Utensílios Domésticos'), ('CLOTHING', 'Vestuário'), ('OUTHER', 'Outros')], default='FOOD', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Cadastrado'), ('AVAILABLE', 'Disponível'), ('RESERVED', 'Reservado'), ('DONATED', 'Doado')], default='REGISTERED', editable=False, max_length=11),
        ),
    ]
