# Generated by Django 2.1.1 on 2018-10-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20181008_0724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
