# Generated by Django 2.1.1 on 2018-10-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20181008_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='DISPONIVEL', max_length=45),
        ),
    ]
