# Generated by Django 2.1.2 on 2018-10-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20181008_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, default='Disponível', max_length=45, null=True),
        ),
    ]
