# Generated by Django 2.1.2 on 2018-10-08 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20181008_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='donor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
