# Generated by Django 2.1.2 on 2018-10-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
